
SKETCHBOOK_DIR=/home/edwin/sketchbook

PROJECT=Blink
MODULES=

ARDUINO_MODEL=Uno
ARDUINO_MODEL=Mega2560
ARDUINO_VER=1.0.6
ARDUINO_VER=1.6.1

INO_FILES= Blink.ino
	
.include "../ledsquare/Makefile.arduino"
