
SKETCHBOOK_DIR=/home/edwin/sketchbook

PROJECT=ledsquare
MODULES=MemoryFree Adafruit_NeoPixel

ARDUINO_MODEL=Uno
ARDUINO_MODEL=Mega2560
ARDUINO_VER=1.6.1
ARDUINO_VER=1.0.6

INO_FILES= \
	LED_Strip.ino		\
	ledsquare.ino
	
SRC_FILES= \
	A_Tools.cpp		\
	LED_Animation.cpp	\
	LED_Slideshow.cpp	\
	LED_Text.cpp		\
	StringEncode.cpp	\
	animations.cpp		\
	animation_squares.cpp	\
	animation_lines.cpp	\
	animation_sinus.cpp	\
	animation_torches.cpp	\
	animation_fractals.cpp	\
	slides.cpp

.include "Makefile.arduino"
