
SKETCHBOOK_DIR=/home/edwin/sketchbook

PROJECT=ledsquare
MODULES=MemoryFree Adafruit_NeoPixel

INO_FILES= \
	LED_Strip.ino		\
	ledsquare.ino
	
SRC_FILES= \
	A_Tools.cpp		\
	LED_Animation.cpp	\
	LED_Slideshow.cpp	\
	LED_Text.cpp		\
	StringEncode.cpp	\
	animations.cpp		\
	animation_squares.cpp	\
	slides.cpp

.include "Makefile.arduino"
