
SKETCHBOOK_DIR=/home/edwin/sketchbook

PROJECT=bmp180
SYSMODULES=Wire
SYSMODULESEXTRA=Wire/utility/twi.c

ARDUINO_MODEL=Mega2560
ARDUINO_MODEL=Uno
ARDUINO_VER=1.0.6
ARDUINO_VER=1.6.1

INO_FILES=altlcd.ino

SRC_FILES=SFE_BMP180.cpp LiquidCrystal.cpp

.include "../ledsquare/Makefile.arduino"
